version: '3.1'
services:
  nginx:
    image: 'binhotvn/nginx-proxy-manager-with-pagespeed:latest'
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    networks:
      - public
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
  image_handler:
    image: 'leadthechange/ltc_image_handler:latest'
    restart: always
    networks:
      - public
    env_file:
      - ./penv/.prod.env
  prod-backend:
    image: 'binhotvn/yet-backend:latest'
    restart: always
    networks:
      - public
    env_file:
      - ./penv/.prod.env
  jenkins:
    image: 'binhotvn/jenkins:latest'
    restart: unless-stopped
    privileged: true
    user: root
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - public
  portainer-ce:
    ports:
        - '8000:8000'
        - '9443:9443'
    container_name: portainer
    restart: always
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
        - './portainer_data:/data'
    image: 'portainer/portainer-ce:latest'
    networks:
      - public

  redis:
    container_name: redis
    restart: always
    image: 'redis:latest'
    networks:
      - public
    volumes:
        - './redis-data:/data'
    
    env_file:
      - ./penv/.prod.env
networks:
  public:
    driver: bridge